services:
  - type: web
    name: sociologic-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_PIN
        sync: false
